# Generated by Django 2.2.3 on 2019-08-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0002_auto_20190807_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vendedor_pedido', to='Buy.Usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador_pedido', to='Buy.Usuario'),
        ),
        migrations.AlterField(
            model_name='puntuacionvendedor',
            name='id_comprador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comprador_puntuacion', to='Buy.Usuario'),
        ),
        migrations.AlterField(
            model_name='puntuacionvendedor',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_puntuacion', to='Buy.Usuario'),
        ),
    ]
