# Generated by Django 2.2.3 on 2019-08-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0003_auto_20190809_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='donacion',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=None),
        ),
    ]
