# Generated by Django 2.2.3 on 2019-08-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0004_auto_20190818_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulopedido',
            name='cantidad',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_venta',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='puntuacionvendedor',
            name='puntuacion',
            field=models.IntegerField(default=None),
        ),
    ]
