# Generated by Django 2.2.3 on 2019-08-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0005_auto_20190818_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateField(default=None),
        ),
    ]
