# Generated by Django 2.2.3 on 2019-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0006_auto_20190818_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descrip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
