# Generated by Django 2.2.3 on 2019-08-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0007_auto_20190831_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=80),
        ),
    ]
